stages:
    - build
    - docker-image
    - deploy

workflow:
  rules:
    # TEST CI_COMMIT_BRANCH
    - if: ($CI_COMMIT_TAG != null || $CI_COMMIT_BRANCH == "chore/cicd")
      when: always
    - when: never

# TODO testing
# testing:
#   stage: build
#   tags:
#     - dev-runner3
#   image: node:14.17.2
#   script:
#     - echo "some code test"

build:
  stage: build
  tags:
    - dev-runner3
  image: node:14.17.2
  # needs:
  #   - testing
  artifacts:
    expire_in: '2 weeks and 1 day'
    when: on_success
    paths:
      - dist
  script:
    - yarn install
    - yarn build

docker-image:
  stage: docker-image
  tags:
    - dev-runner3
  image: docker:18.09.7
  dependencies:
    - build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD "$CI_REGISTRY"
  script:
    - docker build -t $CI_REGISTRY_IMAGE:vocabulary-frontend_v$CI_COMMIT_TAG .
    # push to gitlab registry
    - docker push $CI_REGISTRY_IMAGE:vocabulary-frontend_v$CI_COMMIT_TAG

deploy:
  stage: deploy
  tags:
    - dev-runner3
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get -y install openssh-client)"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GCP_PRIVATE_KEY")
  script:
    - scp -o StrictHostKeyChecking=no ./docker-compose.yml $GCP_USER@$GCP_VOCABULARY_FRONTEND_SERVER:/home/$GCP_USER
    - ssh -o StrictHostKeyChecking=no $GCP_USER@$GCP_VOCABULARY_FRONTEND_SERVER "

      export IMAGE_NAME=$CI_REGISTRY_IMAGE:vocabulary-frontend_v$CI_COMMIT_TAG
      # avoid other docker-compose project been down if have other docker container run the same vm
      export COMPOSE_PROJECT_NAME=front_stage

      docker-compose down &&
      docker-compose up -d
      "
  environment:
    name: dev
    url: http://$GCP_VOCABULARY_FRONTEND_SERVER