stages:
    - build
    - push_image
    - deploy

testing:
  stage: build
  only:
    - tags
    #TEST
    - chore/cicd
  script:
    - echo "some code test"

build:
  stage: build
  only:
    - tags
    #TEST
    - chore/cicd
  needs:
    - testing
  script:
    - echo "hello build"

push_image:
  stage: push_image
  only:
    - tags
    #TEST
    - chore/cicd
  script:
    - echo "hello push_image"

deploy:
  stage: deploy
  only:
    - tags
    #TEST
    - chore/cicd
  script:
    - echo "hello deploy"