stages:
    - build
    - push_image
    - deploy

workflow:
  rules:
    # TEST CI_COMMIT_BRANCH
    - if: ($CI_COMMIT_TAG != null || $CI_COMMIT_BRANCH == "chore/cicd")
      when: always
    - when: never

testing:
  stage: build
  # tags:
    # - dev-runner
  image: node:14.17.2
  script:
    - echo "some code test"

build:
  stage: build
  # tags:
    # - dev-runner
  image: node:14.17.2
  needs:
    - testing
  script:
    - yarn install
    - yarn build

push_image:
  stage: push_image
  # tags:
  #   - dev-runner
  image: docker:20.0.20
  script:
    - echo "hello push_image"

deploy:
  stage: deploy
  # tags:
  #   - dev-runner
  script:
    - echo "hello deploy"