stages:
    - build
    - push_image
    - deploy

testing:
  stage: build
  script:
    - echo "some code test"

build:
  stage: build
  needs:
    - testing
  script:
    - echo "hello build"

push_image:
  stage: push_image
  script:
    - echo "hello push_image"

deploy:
  stage: deploy
  script:
    - echo "hello deploy"